### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [gynamics/zsh-gitneko#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by gynamics** [comment]
My pleasure. Would you accept something like [rimo revolution license](https://github.com/RimoChan/Je-Suis-Le-Deluge) (more or less than a DWTFYW license)?

**Comment by unixorn** [comment]
I'll accept any license - it's more that there is a license for people to decide they're ok with instead of no license, where technically it's copyright by you with no usage rights for anyone else.

I do recommend MIT instead of more exotic ones if you don't care what people do with it, since people are more likely to know and understand MIT and it's widely used.

**Comment by gynamics** [comment]
I agree with you, an MIT license has been added.
However, actually rimo revolution license is a license far beyond DWTFYW, because it needs a communist-style revolution that revolts intellectual property to implement :> just joking
